// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CTSP.API.Models
{
    public partial class SPR_UserWithProfileResult
    {
        public int EnableSaveObt { get; set; }
        public short? DistrictID { get; set; }
        public short? TehsilID { get; set; }
        public string Pic { get; set; }
        public byte? RelationShipID { get; set; }
        public string FHName { get; set; }
        public string FcellNo { get; set; }
        public string CNIC { get; set; }
        public string CNICFPic { get; set; }
        public string CNICBPic { get; set; }
        public string DOB { get; set; }
        public byte? Genderid { get; set; }
        public short? CityID { get; set; }
        public string OtherReligion { get; set; }
        public string FullName { get; set; }
        public string CellNo { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public bool? isLocked { get; set; }
        public long? UserPID { get; set; }
        public string CityName { get; set; }
        public string DisablitySource { get; set; }
        public long? Expr2 { get; set; }
        public string UCName { get; set; }
        public string EduDofJoin { get; set; }
        public string GovtDofJoin { get; set; }
        public string PostalAddress { get; set; }
        public short? MaritalStatus { get; set; }
        public short? Religion { get; set; }
        public short? isHafizQuran { get; set; }
        public short? isDisable { get; set; }
        public short? isCAgeRelax { get; set; }
        public short? isGovtEmp { get; set; }
        public short? isEduDept { get; set; }
        public string District { get; set; }
        public string Tehsil { get; set; }
    }
}
