// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CTSP.API.Models
{
    public partial class SPR_UsersinfoResult
    {
        public long UserID { get; set; }
        public string UserName { get; set; }
        public byte? RoleID { get; set; }
        public string FullName { get; set; }
        public string CellNo { get; set; }
        public string Email { get; set; }
        public string Roles { get; set; }
        public short? isVerified { get; set; }
        public long? PostID { get; set; }
    }
}
