// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CTSP.API.Models
{
    public partial class SPR_UsersDoucmentResult
    {
        public long AttachID { get; set; }
        public string ImageSRC { get; set; }
        public string UploadDate { get; set; }
        public string Title { get; set; }
        public string MissingImg { get; set; }
    }
}
