// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CTSP.API.Models
{
    public partial class SPR_ViewQCPrintDataResult
    {
        public string str20 { get; set; }
        public long? str2 { get; set; }
        public long INT1 { get; set; }
        public string str3 { get; set; }
        public string STR15H { get; set; }
        public string STR19 { get; set; }
        public string str14 { get; set; }
        public string str18 { get; set; }
        public string str8 { get; set; }
        public string str6 { get; set; }
        public string str9 { get; set; }
        public string str11 { get; set; }
        public string str7 { get; set; }
        public string str5 { get; set; }
        public string str4 { get; set; }
        public string str16 { get; set; }
        public string str15 { get; set; }
        public string TehsilName { get; set; }
        public string STR5H { get; set; }
        public string STR9H { get; set; }
        public string STR6H { get; set; }
        public string str12 { get; set; }
        public string STR10H { get; set; }
        public string STR8H { get; set; }
        public string str13 { get; set; }
        public string str1H { get; set; }
        public string str2h { get; set; }
        public string str3h { get; set; }
        public string STR4H { get; set; }
        public string STR25 { get; set; }
        public string str10 { get; set; }
        public string str13H { get; set; }
        public string Pic { get; set; }
        public string STR1 { get; set; }
        public string S65 { get; set; }
        public string s61 { get; set; }
        public string s60 { get; set; }
        public string s63 { get; set; }
        public string s62 { get; set; }
        [Column(TypeName = "decimal(16,0)")]
        public decimal? s64 { get; set; }
        public string S59 { get; set; }
        public string S58 { get; set; }
        public string S69 { get; set; }
        public string S66 { get; set; }
        public string STR13H { get; set; }
        public string STR11H { get; set; }
        public string STR14H { get; set; }
        public string STR12H { get; set; }
    }
}
