// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CTSP.API.Models
{
    public partial class SPR_QCBatchResult
    {
        public short QBID { get; set; }
        public string Title { get; set; }
        public long? StartRange { get; set; }
        public long? endRange { get; set; }
    }
}
