// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CTSP.API.Models
{
    public partial class SPR_QCUsersResult
    {
        public long UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string CellNo { get; set; }
        public int? StatusID { get; set; }
        public int? ShiftID { get; set; }
        public string Statuss { get; set; }
        public string Shifts { get; set; }
        public string Batch { get; set; }
    }
}
