// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CTSP.API.Models
{
    public partial class SPR_PostApplyResult
    {
        public long PostsID { get; set; }
        public string PostsTitle { get; set; }
        public string PostCode { get; set; }
        public byte? BPS { get; set; }
        public string AdvCloseDate { get; set; }
        public long? UserJID { get; set; }
        public string Tracking { get; set; }
        public string ApplyDate { get; set; }
    }
}
