// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CTSP.API.Models
{
    public partial class SPR_PrintDataResult
    {
        public long INT1 { get; set; }
        public string STR1 { get; set; }
        public string STR2 { get; set; }
        public string str3 { get; set; }
        public string STR15H { get; set; }
        public string STR19 { get; set; }
        public string str14 { get; set; }
        public string str18 { get; set; }
        public string str8 { get; set; }
        public string str6 { get; set; }
        public string str9 { get; set; }
        public string str11 { get; set; }
        public string str7 { get; set; }
        public string str5 { get; set; }
        public string str4 { get; set; }
        public string str16 { get; set; }
        public string str15 { get; set; }
        public string TehsilName { get; set; }
        public string STR5H { get; set; }
        public string STR9H { get; set; }
        public string STR6H { get; set; }
        public string str12 { get; set; }
        public string STR10H { get; set; }
        public string STR8H { get; set; }
        public string str13 { get; set; }
        public string str1H { get; set; }
        public string str2h { get; set; }
        public string str3h { get; set; }
        public string STR4H { get; set; }
        public string STR25 { get; set; }
        public string str10 { get; set; }
        public string str13H { get; set; }
        public string Pic { get; set; }
        public string STR14H { get; set; }
        public string STR11H { get; set; }
        public string str12h { get; set; }
    }
}
