// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CTSP.API.Models
{
    public partial class Spr_CertificateResult
    {
        public short CertificateID { get; set; }
        public string Certificate { get; set; }
        public bool? TypeID { get; set; }
    }
}
