// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CTSP.API.Models
{
    public partial class Spr_AcademicResult
    {
        public short CertificateID { get; set; }
        public string Certificate { get; set; }
        public long? UserAID { get; set; }
        public string Title { get; set; }
        public string Subjects { get; set; }
        public int? PassYear { get; set; }
        public double? TMarks { get; set; }
        public double? OMarks { get; set; }
        public string Board { get; set; }
    }
}
