// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CTSP.API.Models
{
    public partial class SPR_PrintRollnoSlipResult
    {
        public long TrackingNo { get; set; }
        public string Post { get; set; }
        public string FullName { get; set; }
        public string FHName { get; set; }
        public string District { get; set; }
        public string Tehsil { get; set; }
        public string UCName { get; set; }
        public string TestCenter { get; set; }
        public string Hall { get; set; }
        public string Section { get; set; }
        public string PaperColor { get; set; }
        public long? RollNo { get; set; }
        public string cnic { get; set; }
        public double? TracingNo { get; set; }
        public string TestDate { get; set; }
        public string Pic { get; set; }
        public string TestTime { get; set; }
        public string ReportingTime { get; set; }
        public string RColumn { get; set; }
        public string PaperCode { get; set; }
    }
}
