// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CTSP.API.Models
{
    public partial class SPR_AcceptedRejectedListResult
    {
        public long? UserJID { get; set; }
        public long UserID { get; set; }
        public string FullName { get; set; }
        public string FHName { get; set; }
        public string PostsTitle { get; set; }
        public double? AcadMarks { get; set; }
        public double? ProfMarks { get; set; }
        public string Pic { get; set; }
        public string District { get; set; }
        public string Tehsil { get; set; }
        public string UCName { get; set; }
        public string JobStatusid { get; set; }
    }
}
