// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CTSP.API.Models
{
    public partial class SPR_QCReviewResult
    {
        public string PostsTitle { get; set; }
        public long? TrackingID { get; set; }
        public string QDate { get; set; }
        public string Query { get; set; }
        public short? Statusid { get; set; }
        public double? TracingNo { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
    }
}
