// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CTSP.API.Models
{
    public partial class SPR_DistrictResult
    {
        public short DistrictID { get; set; }
        public string District { get; set; }
        public short? DivisionID { get; set; }
    }
}
