// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CTSP.API.Models
{
    public partial class SPR_QCViewSubmitResults_backupResult
    {
        public long UserJID { get; set; }
        public string AcadMarks { get; set; }
        public string ProfMarks { get; set; }
        public string PostsTitle { get; set; }
        public double? TracingNo { get; set; }
        public string JobStatus { get; set; }
    }
}
