// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CTSP.API.Models
{
    public partial class SPR_UCResult
    {
        public short UCID { get; set; }
        public string UCName { get; set; }
        public short? TehsilID { get; set; }
        public string UCCode { get; set; }
        public string UCFCode { get; set; }
    }
}
