// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CTSP.API.Models
{
    public partial class SPR_ProvinceResult
    {
        public short? ProvinceID { get; set; }
        public string Province { get; set; }
        public short? CountryID { get; set; }
    }
}
